# Explore your data file some more
- We are continuing (from Colab 12) our work on data exploring using pandas.

In [1]:
### Import package(s)
import pandas as pd

In [2]:
csvFile = 'https://raw.githubusercontent.com/csbfx/advpy122-data/master/top_movies_2020.csv'

movies = pd.read_csv(csvFile)
movies.head()

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965
3          E.T. the Extra-Terrestrial  435110554        1329174791  1982
4                             Titanic  659363944        1270101626  1997

## Filtering DataFrame with string datatype
You can search for instances of a substring in a column using str.contains(), `df[colname].str.contain(<str>)`. The method will return table that meets the condition. If you want to return a single column you can define which column to print `df[df[colname].str.contain(<str>)][colname2]`.

### Series to list
To convert a Series to a list use `series.tolist()`

In [5]:
### You can search for instances of a substring in a column and return rows
## Search for substring (str.contains) and return the table
movies[movies['Title'].str.contains("man")]

## You can print just the column 'Title'

## To convert this Series to a list use series.tolist()

['The Ten Commandments',
 'Batman',
 'Superman',
 'Wonder Woman',
 'Jumanji: Welcome to the Jungle',
 'An Officer and a Gentleman',
 'Batman Forever',
 'Pretty Woman']

### Working with the list
Once you have the list, how do you:
1. How to find out how many elements there are in your list?  
2. How to get the first 5 elements in the list?

In [6]:
### To retrieve the number of elements in the list use len()
len()

### To retrieve the first 5 elements of the list, use a slice

['The Ten Commandments',
 'Batman',
 'Superman',
 'Wonder Woman',
 'Jumanji: Welcome to the Jungle']

### Finding unique values
We can retrieve unique values to ask:
1. How many times an item occurs in a column?
2. To extract out distinct observation elements in a column
3. To count the number of distinct observations in a column

In [ ]:
### To count the number of times a unique item is found in a column we can use value_count()

### To extract out the unique values in a column using the unique() method

### To quantify how many unique using the nunique() method

### Question 13.1: How many distinct movies came out in the 1990s?
To find the number of distinct movies during these years:
1. Filter out the DataFrame based on conditions of the year
2. Get the length `len()` (number of rows) of your filtered DataFrame
  
-or-   
1. Use the str approach to find all years in 1990s (ie., "199")

In [7]:
### Filter out the DataFrame based on conditions of the year combine with len
### Your code
len(<condition statement>)

29

In [8]:
### Use the str approach to find all years in 1990s
### Your code

movies[movies['Year'].astype(str).str.contains("199")]

29

### Question 13.2: How many distinct movies came out for each decade?
Can you write a for loop to iterate through all the decades?

In [ ]:
### Your code

In [ ]:
# decades=['191','192','193','194','195','196','197','198','199','200','201','202']

### Working with string elements
We can think of string as a list of elements. In a column with string datatype, we can split the string `str` using the `split()` method.

In [10]:
### The split method takes a string and split it into a list


## To extract the first element and place it into a new column, assign the new column and run split and extract first element

,Title,Gross,Gross (Adjusted),Year,first_word
0,Gone with the Wind,200852579,1895421694,1939,Gone
1,Star Wars: Episode IV - A New Hope,460998507,1668979715,1977,Star
2,The Sound of Music,159287539,1335086324,1965,The
3,E.T. the Extra-Terrestrial,435110554,1329174791,1982,E.T.
4,Titanic,659363944,1270101626,1997,Titanic
...,...,...,...,...,...
195,Patton,61749765,373287682,1970,Patton
196,Fatal Attraction,156645693,371808159,1987,Fatal
197,Iron Man 2,312433331,371691971,2010,Iron
198,Zootopia,341268248,371109157,2016,Zootopia
199,Liar Liar,181410615,370330510,1997,Liar

### Question 13.3: Can you extract the last element of title
To extract the last element and place it into a new column, 'last word'

In [11]:
### Your code

,Title,Gross,Gross (Adjusted),Year,first_word,last_word
0,Gone with the Wind,200852579,1895421694,1939,Gone,Wind
1,Star Wars: Episode IV - A New Hope,460998507,1668979715,1977,Star,Hope
2,The Sound of Music,159287539,1335086324,1965,The,Music
3,E.T. the Extra-Terrestrial,435110554,1329174791,1982,E.T.,Extra-Terrestrial
4,Titanic,659363944,1270101626,1997,Titanic,Titanic
...,...,...,...,...,...,...
195,Patton,61749765,373287682,1970,Patton,Patton
196,Fatal Attraction,156645693,371808159,1987,Fatal,Attraction
197,Iron Man 2,312433331,371691971,2010,Iron,2
198,Zootopia,341268248,371109157,2016,Zootopia,Zootopia
199,Liar Liar,181410615,370330510,1997,Liar,Liar